### ISSUE TITLE
cron issue

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppet-atomia#227]
Cron agent is failing with this two exceptions.
The #2 happens when you try to delete cron task from HCP.

#1
Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it

#2
Cannot read property 'ObjectID' of undefined
TypeError: Cannot read property 'ObjectID' of undefined
at Route.exports.listoneitem (/usr/lib/atomia-cronagent/controllers/task_controller.js:140:86)
at next (/usr/lib/atomia-cronagent/node_modules/restify/lib/route.js:356:25)
at Route.<anonymous> (/usr/lib/atomia-cronagent/server.js:31:10)
at next (/usr/lib/atomia-cronagent/node_modules/restify/lib/route.js:356:25)
at Route.parseBody (/usr/lib/atomia-cronagent/node_modules/restify/lib/plugins/body_parser.js:16:14)
at next (/usr/lib/atomia-cronagent/node_modules/restify/lib/route.js:356:25)
at Route.parseUrlEncodedBody (/usr/lib/atomia-cronagent/node_modules/restify/lib/plugins/form_body_parser.js:38:14)
at next (/usr/lib/atomia-cronagent/node_modules/restify/lib/route.js:356:25)
at Route.parseQueryString (/usr/lib/atomia-cronagent/node_modules/restify/lib/plugins/query.js:39:12)
at next (/usr/lib/atomia-cronagent/node_modules/restify/lib/route.js:356:25)

-- Nodemailer workarround
apt-get install npm
cd /usr/lib/atomia-cronagent
npm remove nodemailer
npm install nodemailer@0.7.1 --save

-- MongoDB workarround
/usr/lib/atomia-cronagent/controllers/task_controller.js

- var BSON = require('mongodb').BSONPure;
+ var BSON = require('mongodb');

**Comment by stefanmortensen** [comment]
Thanks for the report. I can't see that these issues are related to the puppet module though. Both of these issues should/can be fixed in the cron agent directly.

**Comment by markotrickovic** [comment]
Yeah, makes sense. But i thought it to be as a note for installation ppl until it is fixed. :P
