### ISSUE TITLE
Daggre service won't start

### ISSUE THREAD

**Issue by zeljko-atomia** [atomia/puppet-atomia#250]
Upon daggre machine provisioning daggre service is not started. Checking the logs shows:
```
Jun 21 01:40:50 localhost daggre: Server running at http://*:999/
Jun 21 01:40:50 localhost daggre:
Jun 21 01:40:50 localhost daggre: /usr/lib/daggre/node_modules/mongodb/lib/utils.js:99
Jun 21 01:40:50 localhost daggre:     process.nextTick(function() { throw err; });
Jun 21 01:40:50 localhost daggre:                                         ^
Jun 21 01:40:50 localhost daggre: error ensuring index on object_name
Jun 21 01:41:42 localhost daggre: Server running at http://*:999/
Jun 21 01:41:42 localhost daggre:
Jun 21 01:41:42 localhost daggre: /usr/lib/daggre/node_modules/mongodb/lib/utils.js:99
Jun 21 01:41:42 localhost daggre:     process.nextTick(function() { throw err; });
Jun 21 01:41:42 localhost daggre:                                         ^
Jun 21 01:41:42 localhost daggre: error ensuring index on object_name
```

A little bit more digging shows that the issue is that daggre can't connect to the mongodb:
```
Jun 21 02:06:13 localhost daggre: MongoError: not authorized for query on daggre.system.indexes
Jun 21 02:06:13 localhost daggre:     at Function.MongoError.create (/usr/lib/daggre/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
Jun 21 02:06:13 localhost daggre:     at queryCallback (/usr/lib/daggre/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:198:34)
Jun 21 02:06:13 localhost daggre:     at /usr/lib/daggre/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:455:18
Jun 21 02:06:13 localhost daggre:     at process._tickCallback (node.js:355:11)
```

**Comment by zeljko-atomia** [comment]
https://github.com/atomia/puppet-atomia/pull/251 fixes the issue, but only for Ubuntu 14.04.

Need more investigation for 16.04
